### ISSUE TITLE
Unhandled exception - Can't access games

### ISSUE THREAD

**Issue by Lazar911** [rhdpin/nhltv-fetcher#1]
When I type in (Windows 11, tried Powershell and cmd):

`./nhltv-fetcher -c -p /Downloads`

I get the following error message:

```
Unhandled exception. System.Text.Json.JsonException: The JSON value could not be converted to System.Int32. Path: $.meta.from | LineNumber: 0 | BytePositionInLine: 196.
 ---> System.InvalidOperationException: Cannot get the value of a token type 'Null' as a number.
   at System.Text.Json.Utf8JsonReader.TryGetInt32(Int32& )
   at System.Text.Json.Utf8JsonReader.GetInt32()
   at System.Text.Json.Serialization.Converters.Int32Converter.Read(Utf8JsonReader& , Type , JsonSerializerOptions )
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object , ReadStack& , Utf8JsonReader& )
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& , Type , JsonSerializerOptions , ReadStack& , T& )
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& , Type , JsonSerializerOptions , ReadStack& , T& )
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object , ReadStack& , Utf8JsonReader& )
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& , Type , JsonSerializerOptions , ReadStack& , T& )
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& , Type , JsonSerializerOptions , ReadStack& , T& )
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& , JsonSerializerOptions , ReadStack& )
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& , Utf8JsonReader& , Exception )
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& , JsonSerializerOptions , ReadStack& )
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 , JsonTypeInfo , Nullable`1 )
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 , JsonTypeInfo )
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String , JsonSerializerOptions )
   at NhlTvFetcher.FeedFetcher.GetSchedule(DateTime start, DateTime end) in D:\a\nhltv-fetcher\nhltv-fetcher\src\FeedFetcher.cs:line 156
   at NhlTvFetcher.FeedFetcher.GetFeeds(DateTime start, DateTime end) in D:\a\nhltv-fetcher\nhltv-fetcher\src\FeedFetcher.cs:line 169
   at NhlTvFetcher.FeedManager.ChooseFeed(String targetPath, Boolean getOnlyUrl) in D:\a\nhltv-fetcher\nhltv-fetcher\src\FeedManager.cs:line 37
   at NhlTvFetcher.Program.<>c.<Main>b__5_3(Options options) in D:\a\nhltv-fetcher\nhltv-fetcher\src\Program.cs:line 70
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at NhlTvFetcher.Program.Main(String[] args) in D:\a\nhltv-fetcher\nhltv-fetcher\src\Program.cs:line 55
```

I configured the mail and password for NHL.TV and double checked, they are correct.

Is this a bug or expected because the season starts today and there are no games to browse (the 2023 Stanley Cup Final games should appear, shouldn't they?)

Thanks for this tool and your work! :)

**Comment by rhdpin** [comment]
Sorry for not commenting earlier (I hadn't checked the email for this account for a long time and I had not tried the application previously this season).

Some NHL APIs were changed for this season, so constructing the game feed information had to be made differently. There was also another issue related to download address handling (HTTPS needs to be used now).

These problems have now been fixed in release [v1.0.2](https://github.com/rhdpin/nhltv-fetcher/releases/tag/v1.0.2). So if you're still interested in this application, please check out the latest version now.
